# Generated by Django 4.2 on 2025-08-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_shipment_amount_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveupdate',
            old_name='current_location',
            new_name='country',
        ),
        migrations.AddField(
            model_name='liveupdate',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveupdate',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
