# Generated by Django 4.2 on 2025-08-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_shipment_receiver_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipping_date',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
